import React, { useState } from "react";
import PropTypes from "prop-types";
import { PENDING } from "unchained-wallets";

import { Button, FormHelperText, Grid } from "@material-ui/core";

import KeystoneRawReader from "./KeystoneRawReader";

const KeystoneReader = (props) => {
  const [status, setStatus] = useState(PENDING);
  const [error, setError] = useState("");
  const {
    interaction,
    qrStartText,
    fileStartText,
    shouldShowFileReader,
    fileType,
    onClear,
    onSuccess,
    disable,
  } = props;

  const handleError = (err) => {
    setStatus("error");
    setError(err.message);
    if (onClear) {
      onClear();
    }
  };

  const handleSuccess = (result) => {
    onSuccess(result);
    setStatus("success");
  };

  const handleStop = () => {
    setStatus(PENDING);
    setError("");
    if (onClear) {
      onClear();
    }
  };

  if (status === PENDING) {
    const commandMessages = interaction.messagesFor({
      state: status,
      code: "keystone.command",
    });
    return (
      <div>
        {commandMessages.map((message, index) => {
          // eslint-disable-next-line react/no-array-index-key
          return <p key={`message${index}`}>{message.instructions}</p>;
        })}
        <p>
          When you are ready, scan the QR code produced by Keystone or upload
          the file generated by Keystone:
        </p>
        <Grid container spacing={2}>
          <KeystoneRawReader
            shouldShowFileReader={shouldShowFileReader}
            fileStartText={fileStartText}
            qrStartText={qrStartText}
            interaction={interaction}
            handleError={handleError}
            handleSuccess={handleSuccess}
            handleStop={handleStop}
            fileType={fileType}
            disable={disable}
          />
        </Grid>
      </div>
    );
  }

  if (status === "error" || status === "success") {
    return (
      <div>
        <FormHelperText error>{error}</FormHelperText>
        <Button
          variant="contained"
          color="secondary"
          size="small"
          onClick={handleStop}
        >
          Reset
        </Button>
      </div>
    );
  }

  return null;
};

KeystoneReader.propTypes = {
  onSuccess: PropTypes.func.isRequired,
  onClear: PropTypes.func.isRequired,
  qrStartText: PropTypes.string,
  shouldShowFileReader: PropTypes.bool.isRequired,
  fileStartText: PropTypes.string,
  interaction: PropTypes.shape({
    messagesFor: PropTypes.func,
    parse: PropTypes.func,
  }).isRequired,
  fileType: PropTypes.string,
  disable: PropTypes.bool,
};

KeystoneReader.defaultProps = {
  qrStartText: "",
  fileStartText: "",
  fileType: "json",
  disable: false,
};

export default KeystoneReader;
